# -*- coding: utf-8 -*-
"""Merge_Sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcFWwslXGNnk-QooCVGbxVuaHlnSwxUJ
"""

import random

def merge_sort(arr):
  if len(arr) == 1:
    return arr
  mid = len(arr) // 2
  left = merge_sort(arr[:mid])
  right = merge_sort(arr[mid:])
  return merge(left, right)

def merge(arr1, arr2):
  i = 0
  j = 0
  result = []
  while i < len(arr1) and j < len(arr2):
    if arr1[i] < arr2[j]:
      result.append(arr1[i])
      i += 1
    else:
      result.append(arr2[j])
      j += 1
  result.extend(arr1[i:])
  result.extend(arr2[j:])
  return result

def bubble_sort(arr):
  for i in range(len(arr)):
    for j in range(len(arr) - i - 1):
      if arr[j] > arr[j + 1]:
        arr[j], arr[j + 1] = arr[j + 1], arr[j]
  return arr

random_array = [random.randint(1, 50) for i in range(50)]
print(random_array)

print(merge_sort(random_array))

print(bubble_sort(random_array))